<x-admin-layout>
<x-slot name="header">
    <div class="text-right">
        <h1 class="text-2xl font-black text-slate-900">Bosta للشحن</h1>
        <p class="mt-1 text-sm text-slate-500">إنشاء الشحنات وطلبات الاستلام ومتابعة حالة التوصيل.</p>
    </div>
</x-slot>
<div class="space-y-6" dir="rtl">
 @if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-800">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="rounded-2xl bg-red-50 p-4 text-red-800"><ul class="list-disc pr-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 <section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-xl font-black">حالة الربط</h2><p class="mt-1 text-sm text-gray-500">COD معلومة تشغيلية للشحن فقط ولا يُسجل كدفعة أو تحصيل داخل HeroKid.</p></div><span class="rounded-full px-4 py-2 font-bold {{ $configured ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">{{ $configured ? 'جاهز' : 'يحتاج إعداد .env' }}</span></div></section>
 @can('bosta.create_shipment')<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-xl font-black">طلبات جاهزة لإنشاء شحنة</h2><p class="mt-1 text-xs font-bold text-gray-500">تظهر هنا للمراجعة فقط. افتح الطلب لمراجعة بيانات المستلم والعنوان وCOD ثم إنشاء الشحنة.</p><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">@forelse($eligibleOrders as $order)<div class="rounded-2xl border p-4"><div class="font-black">{{ $order->checkoutReference?->short_reference ?: $order->order_number }}</div><div class="mt-1 text-sm text-gray-600">{{ $order->parent_name }} · {{ data_get($order->delivery_details, 'governorate') }}</div><a href="{{ route('admin.orders.show', $order) }}#order-bosta-shipping" class="mt-3 block w-full rounded-xl bg-indigo-600 px-4 py-2 text-center font-bold text-white">فتح ومراجعة الطلب</a></div>@empty<p class="text-gray-500">لا توجد عمليات شراء حالتها جاهز للشحن.</p>@endforelse</div></section>@endcan
 <section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-black">شحنات بانتظار Pickup</h2><p class="mt-1 text-xs font-bold text-gray-500">الشحنات التي تم إنشاؤها ولم تُضف إلى طلب استلام بعد.</p></div><span class="text-sm text-gray-500">{{ $shipments->total() }} شحنة</span></div>
@if($shipments->isNotEmpty())<form method="POST" action="{{ route('admin.bosta.pickups.store') }}" class="mt-4">@csrf<div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-gray-500"><th class="p-3"></th><th class="p-3 text-right">الطلب</th><th class="p-3 text-right">التتبع</th><th class="p-3 text-right">حالة Bosta</th><th class="p-3 text-right">COD تشغيلي</th><th class="p-3 text-right">آخر تحديث</th></tr></thead><tbody>@foreach($shipments as $shipment)<tr class="border-b"><td class="p-3"><input type="checkbox" name="shipments[]" value="{{ $shipment->id }}" class="rounded"></td><td class="p-3 font-bold">{{ $shipment->business_reference }}</td><td class="p-3" dir="ltr">{{ $shipment->tracking_number }}</td><td class="p-3">{{ $shipment->shipping_status ?: ($shipment->state_code !== null ? 'كود '.$shipment->state_code : 'تم إنشاء الشحنة') }}</td><td class="p-3">{{ format_money($shipment->cod_amount_cents / 100) }}</td><td class="p-3">{{ $shipment->last_event_at?->format('d/m/Y h:i A') ?: $shipment->updated_at?->format('d/m/Y h:i A') }}</td></tr>@endforeach</tbody></table></div>
@can('bosta.create_pickup')<div class="mt-5 grid gap-3 md:grid-cols-4"><label class="text-sm font-bold">تاريخ الاستلام<input type="date" name="scheduled_date" value="{{ now()->addDay()->toDateString() }}" class="mt-1 w-full rounded-xl border-gray-300" required></label><label class="text-sm font-bold">مسؤول التسليم<input name="contact_name" class="mt-1 w-full rounded-xl border-gray-300" required></label><label class="text-sm font-bold">الهاتف<input name="contact_phone" inputmode="tel" class="mt-1 w-full rounded-xl border-gray-300" required></label><label class="text-sm font-bold">ملاحظة<input name="notes" class="mt-1 w-full rounded-xl border-gray-300"></label></div>@endcan
<div class="mt-4 flex flex-wrap gap-3">
    @can('bosta.create_pickup')<button class="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">إنشاء Pickup للشحنات المختارة</button>@endcan
    @can('bosta.print_awb')
        <select name="awb_type" class="rounded-xl border-gray-300 text-sm font-bold"><option value="A6" selected>A6 — طابعة حرارية</option><option value="A4">A4 — طابعة عادية</option></select>
        <button type="submit" formaction="{{ route('admin.bosta.awb') }}" formtarget="_blank" formnovalidate class="rounded-xl bg-slate-900 px-5 py-3 font-bold text-white">فتح بوليصة الشحن</button>
    @endcan
</div></form>@else<p class="mt-4 text-gray-500">لم يتم إنشاء شحنات بعد.</p>@endif<div class="mt-4">{{ $shipments->links() }}</div></section>
 @if($pickups->isNotEmpty())<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-xl font-black">آخر طلبات الاستلام</h2><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach($pickups as $pickup)<div class="rounded-2xl bg-gray-50 p-4"><b>{{ $pickup->scheduled_date->format('d/m/Y') }}</b> · {{ $pickup->number_of_parcels }} شحنة<br><span class="text-sm text-gray-500">{{ $pickup->contact_name }} · {{ $pickup->bosta_pickup_id ?: 'قيد التجهيز' }}</span></div>@endforeach</div></section>@endif
</div>
</x-admin-layout>
