import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';
import { getDeviceValue, setDeviceValue } from '@/src/storage/deviceStorage';
export type Locale = 'ar'|'en';
const copy = {
 ar:{home:'الرئيسية',catalog:'المتجر',children:'أطفالي',cart:'السلة',orders:'طلباتي',profile:'حسابي',heroTitle:'طفلك هو بطل الحكاية',heroBody:'اصنع قصة وهدية شخصية تحمل اسم طفلك وهويته.',explore:'اكتشف المنتجات',freeIdentity:'اصنع هوية طفلك مجاناً',recommended:'مختارة لطفلك',signIn:'تسجيل الدخول',register:'إنشاء حساب',emailOrPhone:'البريد أو رقم الهاتف',password:'كلمة المرور',name:'الاسم',email:'البريد الإلكتروني',phone:'رقم الهاتف',confirmPassword:'تأكيد كلمة المرور',noChildren:'أنشئ ملف طفلك مرة واحدة واستخدمه في كل قصة وطلب.',addChild:'إضافة طفل',age:'العمر',boy:'ولد',girl:'بنت',interests:'الاهتمامات',save:'حفظ',retry:'إعادة المحاولة',loading:'جارٍ التحميل…',error:'تعذر إكمال العملية. حاول مرة أخرى.',startPersonalization:'ابدأ التخصيص',guest:'تصفح كزائر',logout:'تسجيل الخروج',language:'English',emptyOrders:'ستظهر طلباتك ومراحل الإنتاج هنا.',checkout:'إتمام الطلب',addresses:'عناوين التوصيل',addAddress:'إضافة عنوان',promoCode:'كود الخصم',apply:'تطبيق',remove:'حذف',emptyCart:'سلتك فارغة.',selectChild:'اختر الطفل',selectPhotos:'اختر صورتين أو ثلاث صور',dedication:'الإهداء',instructions:'تعليمات إضافية',addToCart:'أضف إلى السلة',terms:'أوافق على الشروط ومعالجة صور الطفل لتنفيذ الطلب',placeOrder:'تأكيد الطلب',signInOtp:'الدخول برقم الهاتف',otpInstructions:'سنرسل رمز تحقق آمن إلى رقم هاتفك.',otpSent:'أدخل رمز التحقق المكون من 6 أرقام.',nameOptional:'الاسم (اختياري للحساب الجديد)',sendCode:'إرسال الرمز',verificationCode:'رمز التحقق',verifyAndContinue:'تحقق ومتابعة',changePhone:'تغيير رقم الهاتف',or:'أو',continueGoogle:'المتابعة باستخدام Google',continueApple:'المتابعة باستخدام Apple',googleNotConfigured:'تسجيل Google يحتاج إلى إضافة معرفات التطبيق في إعدادات الإصدار.',socialTokenMissing:'لم يرسل مزود تسجيل الدخول رمز هوية صالحاً.'},
 en:{home:'Home',catalog:'Shop',children:'My children',cart:'Cart',orders:'Orders',profile:'Profile',heroTitle:'Your child is the hero',heroBody:'Create a personalized story and gift featuring your child.',explore:'Explore products',freeIdentity:'Create a free Child Identity',recommended:'Picked for your child',signIn:'Sign in',register:'Create account',emailOrPhone:'Email or phone',password:'Password',name:'Name',email:'Email',phone:'Phone',confirmPassword:'Confirm password',noChildren:'Create your child profile once and reuse it for every story and order.',addChild:'Add child',age:'Age',boy:'Boy',girl:'Girl',interests:'Interests',save:'Save',retry:'Retry',loading:'Loading…',error:'We could not complete that action. Try again.',startPersonalization:'Start personalization',guest:'Continue as guest',logout:'Log out',language:'العربية',emptyOrders:'Your orders and production progress will appear here.',checkout:'Checkout',addresses:'Delivery addresses',addAddress:'Add address',promoCode:'Promo code',apply:'Apply',remove:'Remove',emptyCart:'Your cart is empty.',selectChild:'Select child',selectPhotos:'Select two or three photos',dedication:'Dedication',instructions:'Additional instructions',addToCart:'Add to cart',terms:'I accept the terms and child-image processing required for this order',placeOrder:'Place order',signInOtp:'Sign in with phone',otpInstructions:'We will send a secure verification code to your phone.',otpSent:'Enter the 6-digit verification code.',nameOptional:'Name (optional for a new account)',sendCode:'Send code',verificationCode:'Verification code',verifyAndContinue:'Verify and continue',changePhone:'Change phone number',or:'or',continueGoogle:'Continue with Google',continueApple:'Continue with Apple',googleNotConfigured:'Google sign-in needs the app client IDs in the release configuration.',socialTokenMissing:'The sign-in provider did not return a valid identity token.'}
} as const;
type Copy=typeof copy.ar; type Value={locale:Locale;isRtl:boolean;t:Copy;l:(arabic:string,english:string)=>string;toggleLocale:()=>void}; const Context=createContext<Value|null>(null);
export function I18nProvider({children}:PropsWithChildren){const[locale,setLocale]=useState<Locale>('ar');useEffect(()=>{void getDeviceValue('herokid.locale').then(saved=>{if(saved==='ar'||saved==='en')setLocale(saved)})},[]);const value=useMemo<Value>(()=>({locale,isRtl:locale==='ar',t:copy[locale] as Copy,l:(arabic,english)=>locale==='ar'?arabic:english,toggleLocale:()=>setLocale(current=>{const next=current==='ar'?'en':'ar';void setDeviceValue('herokid.locale',next);return next})}),[locale]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useI18n(){const value=useContext(Context);if(!value)throw new Error('useI18n must be used inside I18nProvider');return value}
