<?php

return [
    'last_manager_error' => 'لا يمكن تنفيذ العملية لأن النظام يجب أن يحتفظ بمستخدم إداري نشط واحد على الأقل قادر على إدارة الصلاحيات.',

    'groups' => [
        'dashboard' => [
            'name_ar' => 'لوحة القيادة',
            'name_en' => 'Dashboard',
            'sort_order' => 10,
        ],
        'orders' => [
            'name_ar' => 'الطلبات والإنتاج',
            'name_en' => 'Orders and Production',
            'sort_order' => 20,
        ],
        'production_studio' => [
            'name_ar' => 'استوديو الإنتاج',
            'name_en' => 'Production Studio',
            'sort_order' => 25,
        ],
        'child_identities' => [
            'name_ar' => 'هويات الأطفال',
            'name_en' => 'Child Identities',
            'sort_order' => 27,
        ],
        'expenses' => [
            'name_ar' => 'المصروفات',
            'name_en' => 'Expenses',
            'sort_order' => 28,
        ],
        'customers' => [
            'name_ar' => 'العملاء',
            'name_en' => 'Customers',
            'sort_order' => 30,
        ],
        'stories' => [
            'name_ar' => 'القصص',
            'name_en' => 'Stories',
            'sort_order' => 40,
        ],
        'store' => [
            'name_ar' => 'المتجر والمنتجات',
            'name_en' => 'Store and Products',
            'sort_order' => 50,
        ],
        'content' => [
            'name_ar' => 'إدارة المحتوى',
            'name_en' => 'Content',
            'sort_order' => 60,
        ],
        'settings' => [
            'name_ar' => 'الإعدادات والتشغيل',
            'name_en' => 'Settings and Operations',
            'sort_order' => 70,
        ],
        'integrations' => [
            'name_ar' => 'التكاملات',
            'name_en' => 'Integrations',
            'sort_order' => 75,
        ],
        'admin_users' => [
            'name_ar' => 'إدارة المستخدمين والصلاحيات',
            'name_en' => 'Admin Users and Permissions',
            'sort_order' => 80,
        ],
        'activity_logs' => [
            'name_ar' => 'سجل النشاط',
            'name_en' => 'Activity Logs',
            'sort_order' => 90,
        ],
    ],

    'permissions' => [
        'robodesk.view' => ['group_key' => 'integrations', 'name_ar' => 'عرض تكامل RoboDesk', 'name_en' => 'View RoboDesk integration', 'description_ar' => 'عرض حالة التكامل والأحداث وإثباتات الدفع.', 'description_en' => 'View integration status, events, and payment proofs.', 'sort_order' => 10, 'sensitive' => true],
        'robodesk.manage' => ['group_key' => 'integrations', 'name_ar' => 'إدارة تكامل RoboDesk', 'name_en' => 'Manage RoboDesk integration', 'description_ar' => 'إدارة ربط المحادثات وسير عمل العملاء.', 'description_en' => 'Manage customer workflow and conversation linkage.', 'sort_order' => 20, 'sensitive' => true],
        'robodesk.review_payments' => ['group_key' => 'integrations', 'name_ar' => 'مراجعة إثباتات InstaPay', 'name_en' => 'Review InstaPay proofs', 'description_ar' => 'اعتماد أو رفض إثباتات الدفع يدويًا.', 'description_en' => 'Approve or reject payment proofs manually.', 'sort_order' => 30, 'sensitive' => true],
        'robodesk.view_media' => ['group_key' => 'integrations', 'name_ar' => 'عرض إثباتات الدفع', 'name_en' => 'View payment proof media', 'description_ar' => 'فتح ملفات إثبات الدفع الخاصة.', 'description_en' => 'Open private payment proof files.', 'sort_order' => 40, 'sensitive' => true],
        'robodesk.retry' => ['group_key' => 'integrations', 'name_ar' => 'إعادة إرسال أحداث RoboDesk', 'name_en' => 'Retry RoboDesk events', 'description_ar' => 'إعادة محاولة إرسال الأحداث الفاشلة أو المعلقة.', 'description_en' => 'Retry failed or held outbound events.', 'sort_order' => 50, 'sensitive' => true],
        'expenses.view' => ['group_key' => 'expenses', 'name_ar' => 'عرض المصروفات', 'name_en' => 'View expenses', 'description_ar' => 'عرض دفتر الوارد والصادر والرصيد.', 'description_en' => 'View the manual income and expense ledger.', 'sort_order' => 10, 'sensitive' => true],
        'expenses.create_income' => ['group_key' => 'expenses', 'name_ar' => 'إضافة الوارد', 'name_en' => 'Create income', 'description_ar' => 'إضافة وارد أو رصيد افتتاحي يدوي.', 'description_en' => 'Add manual income or opening balances.', 'sort_order' => 20, 'sensitive' => true],
        'expenses.create_expense' => ['group_key' => 'expenses', 'name_ar' => 'إضافة المصروفات', 'name_en' => 'Create expenses', 'description_ar' => 'إضافة مصروف يدوي.', 'description_en' => 'Add manual expense transactions.', 'sort_order' => 30, 'sensitive' => true],
        'expenses.edit' => ['group_key' => 'expenses', 'name_ar' => 'تعديل العمليات المالية', 'name_en' => 'Edit expense transactions', 'description_ar' => 'تعديل العمليات المرحلة غير الملغاة.', 'description_en' => 'Edit posted, non-voided transactions.', 'sort_order' => 40, 'sensitive' => true],
        'expenses.void' => ['group_key' => 'expenses', 'name_ar' => 'إلغاء العمليات المالية', 'name_en' => 'Void expense transactions', 'description_ar' => 'إلغاء أثر عملية مالية مع تسجيل السبب.', 'description_en' => 'Void a transaction with an audited reason.', 'sort_order' => 50, 'sensitive' => true],
        'expenses.view_attachments' => ['group_key' => 'expenses', 'name_ar' => 'عرض مرفقات المصروفات', 'name_en' => 'View expense attachments', 'description_ar' => 'عرض الإيصالات والفواتير الخاصة.', 'description_en' => 'View private receipts and invoices.', 'sort_order' => 60, 'sensitive' => true],
        'expenses.download_attachments' => ['group_key' => 'expenses', 'name_ar' => 'تنزيل مرفقات المصروفات', 'name_en' => 'Download expense attachments', 'description_ar' => 'تنزيل الإيصالات والفواتير الخاصة.', 'description_en' => 'Download private receipts and invoices.', 'sort_order' => 70, 'sensitive' => true],
        'expenses.manage_categories' => ['group_key' => 'expenses', 'name_ar' => 'إدارة تصنيفات المصروفات', 'name_en' => 'Manage expense categories', 'description_ar' => 'إضافة وتعديل وتعطيل تصنيفات الوارد والصادر.', 'description_en' => 'Create, edit, and deactivate ledger categories.', 'sort_order' => 80, 'sensitive' => true],
        'expenses.export' => ['group_key' => 'expenses', 'name_ar' => 'تصدير المصروفات', 'name_en' => 'Export expenses', 'description_ar' => 'تصدير العمليات المالية بصيغة CSV.', 'description_en' => 'Export ledger transactions as CSV.', 'sort_order' => 90, 'sensitive' => true],
        'expenses.view_reports' => ['group_key' => 'expenses', 'name_ar' => 'عرض تقارير المصروفات', 'name_en' => 'View expense reports', 'description_ar' => 'عرض تجميعات الوارد والصادر حسب التصنيف.', 'description_en' => 'View income and expense reporting breakdowns.', 'sort_order' => 100, 'sensitive' => true],
        'child_identities.view' => ['group_key' => 'child_identities', 'name_ar' => 'عرض هويات الأطفال', 'name_en' => 'View child identities', 'description_ar' => 'عرض طلبات هويات الأطفال وسجلها.', 'description_en' => 'View child identity requests and history.', 'sort_order' => 10, 'sensitive' => true],
        'child_identities.view_media' => ['group_key' => 'child_identities', 'name_ar' => 'عرض صور هويات الأطفال', 'name_en' => 'View child identity media', 'description_ar' => 'عرض الصور الأصلية والمخرجات الخاصة.', 'description_en' => 'View private originals and generated outputs.', 'sort_order' => 20, 'sensitive' => true],
        'child_identities.view_costs' => ['group_key' => 'child_identities', 'name_ar' => 'عرض تكاليف هويات الأطفال', 'name_en' => 'View child identity costs', 'description_ar' => 'عرض تكلفة محاولات التوليد بالدولار.', 'description_en' => 'View generation attempt cost in USD.', 'sort_order' => 30, 'sensitive' => true],
        'child_identities.manage_shares' => ['group_key' => 'child_identities', 'name_ar' => 'إدارة مشاركة الهويات', 'name_en' => 'Manage identity shares', 'description_ar' => 'إدارة روابط وبطاقات المشاركة العامة وإيقافها وإعادة توليدها.', 'description_en' => 'Manage public identity share links and cards.', 'sort_order' => 35, 'sensitive' => true],
        'child_identities.view_share_report' => ['group_key' => 'child_identities', 'name_ar' => 'عرض تقرير مشاركة الهويات', 'name_en' => 'View identity share report', 'description_ar' => 'عرض أداء الإحالات والمشاركة بدون بيانات شخصية.', 'description_en' => 'View privacy-safe identity sharing and referral performance.', 'sort_order' => 36, 'sensitive' => false],
        'child_identities.generate' => ['group_key' => 'child_identities', 'name_ar' => 'توليد هويات الأطفال', 'name_en' => 'Generate child identities', 'description_ar' => 'تشغيل وإعادة تشغيل توليد الهوية من الإدارة.', 'description_en' => 'Run and retry identity generation from admin.', 'sort_order' => 40, 'sensitive' => true],
        'child_identities.approve' => ['group_key' => 'child_identities', 'name_ar' => 'اعتماد هويات الأطفال', 'name_en' => 'Approve child identities', 'description_ar' => 'اعتماد أو رفض وتغيير محاولة الهوية المعتمدة.', 'description_en' => 'Approve, reject, or replace the approved identity.', 'sort_order' => 50, 'sensitive' => true],
        'child_identities.delete' => ['group_key' => 'child_identities', 'name_ar' => 'حذف هويات الأطفال مؤقتًا', 'name_en' => 'Soft delete child identities', 'description_ar' => 'نقل طلب الهوية إلى سلة المحذوفات مع الاحتفاظ بالملفات.', 'description_en' => 'Move identity requests to Trash while retaining files.', 'sort_order' => 60, 'sensitive' => true],
        'child_identities.restore' => ['group_key' => 'child_identities', 'name_ar' => 'استعادة هويات الأطفال', 'name_en' => 'Restore child identities', 'description_ar' => 'استعادة طلبات الهوية من سلة المحذوفات.', 'description_en' => 'Restore identity requests from Trash.', 'sort_order' => 70, 'sensitive' => true],
        'child_identities.force_delete' => ['group_key' => 'child_identities', 'name_ar' => 'الحذف النهائي لهويات الأطفال', 'name_en' => 'Permanently delete child identities', 'description_ar' => 'حذف السجلات والملفات نهائيًا بإذن مرتفع منفصل.', 'description_en' => 'Permanently delete records and media with separate elevated permission.', 'sort_order' => 80, 'sensitive' => true],
        'child_identities.settings' => ['group_key' => 'child_identities', 'name_ar' => 'إعدادات هويات الأطفال', 'name_en' => 'Manage child identity settings', 'description_ar' => 'تحديث إعدادات التوليد والبرومبت.', 'description_en' => 'Manage identity generation and prompt settings.', 'sort_order' => 90, 'sensitive' => true],
        'dashboard.view' => [
            'group_key' => 'dashboard',
            'name_ar' => 'عرض لوحة القيادة',
            'name_en' => 'View dashboard',
            'description_ar' => 'عرض صفحة لوحة القيادة والإحصاءات العامة.',
            'description_en' => 'View dashboard and overview metrics.',
            'sort_order' => 10,
        ],
        'analytics.view' => [
            'group_key' => 'dashboard',
            'name_ar' => 'عرض تحليلات الموقع',
            'name_en' => 'View website analytics',
            'description_ar' => 'عرض إحصاءات زيارات الموقع والتحويلات من Google Analytics.',
            'description_en' => 'View website traffic and conversion analytics from Google Analytics.',
            'sort_order' => 20,
            'sensitive' => true,
        ],
        'sales_reports.view' => [
            'group_key' => 'dashboard',
            'name_ar' => 'عرض تقرير المبيعات',
            'name_en' => 'View sales report',
            'description_ar' => 'عرض وتصفية وتصدير قيم الطلبات ومؤشرات المبيعات التفصيلية.',
            'description_en' => 'View, filter, and export detailed order-value and sales metrics.',
            'sort_order' => 25,
            'sensitive' => true,
        ],
        'visitor_carts.view' => [
            'group_key' => 'dashboard',
            'name_ar' => 'عرض سلات الزوار',
            'name_en' => 'View visitor carts',
            'description_ar' => 'عرض السلات المحلية النشطة والمتروكة والمتحولة لطلبات.',
            'description_en' => 'View local active, abandoned, and converted visitor carts.',
            'sort_order' => 30,
            'sensitive' => true,
        ],

        'orders.view' => [
            'group_key' => 'orders',
            'name_ar' => 'عرض الطلبات',
            'name_en' => 'View orders',
            'description_ar' => 'عرض قائمة الطلبات وتفاصيل الطلب.',
            'description_en' => 'View order list and order details.',
            'sort_order' => 10,
        ],
        'orders.create' => [
            'group_key' => 'orders',
            'name_ar' => 'إنشاء طلبات يدوية',
            'name_en' => 'Create manual orders',
            'description_ar' => 'إنشاء طلب عميل يدويًا من الإدارة مع المنتجات والتوصيل والخصم.',
            'description_en' => 'Create customer orders manually with products, delivery, and discounts.',
            'sort_order' => 20,
            'sensitive' => true,
        ],
        'orders.update' => [
            'group_key' => 'orders',
            'name_ar' => 'تحديث الطلبات',
            'name_en' => 'Update orders',
            'description_ar' => 'تحديث حالة الطلب والملاحظات وبيانات التشغيل.',
            'description_en' => 'Update order status, notes, and operational fields.',
            'sort_order' => 30,
        ],
        'orders.preview.upload' => [
            'group_key' => 'orders',
            'name_ar' => 'رفع معاينات التصميم',
            'name_en' => 'Upload previews',
            'description_ar' => 'رفع أو إدارة تصميمات المعاينة الخاصة بالعميل.',
            'description_en' => 'Upload or manage customer design previews.',
            'sort_order' => 30,
        ],
        'orders.photos.view' => [
            'group_key' => 'orders',
            'name_ar' => 'عرض صور الأطفال',
            'name_en' => 'View child photos',
            'description_ar' => 'عرض صور الأطفال وروابط الإنتاج الخاصة بها.',
            'description_en' => 'View child photos and secure production photo links.',
            'sort_order' => 40,
            'sensitive' => true,
        ],
        'orders.production_prompt.manage' => [
            'group_key' => 'orders',
            'name_ar' => 'إدارة برومبت إنتاج الطلب',
            'name_en' => 'Manage order production prompt',
            'description_ar' => 'عرض وتوليد وتعديل وحفظ نسخ برومبت الإنتاج للطلبات.',
            'description_en' => 'View, regenerate, edit, override, reset, and snapshot order production prompts.',
            'sort_order' => 50,
            'sensitive' => true,
        ],
        'orders.delete' => [
            'group_key' => 'orders',
            'name_ar' => 'حذف واستعادة الطلبات',
            'name_en' => 'Delete and restore orders',
            'description_ar' => 'نقل عمليات الشراء أو القصص إلى سلة المحذوفات واستعادتها.',
            'description_en' => 'Move checkouts or story orders to trash and restore them.',
            'sort_order' => 60,
            'sensitive' => true,
        ],

        'booklet_previews.view' => ['group_key' => 'orders', 'name_ar' => 'عرض معاينات الكتب', 'name_en' => 'View booklet previews', 'description_ar' => 'عرض مكتبة معاينات الكتب وروابط العملاء.', 'description_en' => 'View the booklet preview library and customer links.', 'sort_order' => 70, 'sensitive' => true],
        'booklet_previews.create' => ['group_key' => 'orders', 'name_ar' => 'إنشاء معاينات الكتب', 'name_en' => 'Create booklet previews', 'description_ar' => 'رفع ملفات PDF وإنشاء روابط معاينة خاصة.', 'description_en' => 'Upload PDFs and create private preview links.', 'sort_order' => 71, 'sensitive' => true],
        'booklet_previews.update' => ['group_key' => 'orders', 'name_ar' => 'تحديث معاينات الكتب', 'name_en' => 'Update booklet previews', 'description_ar' => 'تعديل بيانات المعاينة ورفع إصدارات مصححة.', 'description_en' => 'Edit previews and upload corrected versions.', 'sort_order' => 72, 'sensitive' => true],
        'booklet_previews.publish' => ['group_key' => 'orders', 'name_ar' => 'نشر معاينات القصص', 'name_en' => 'Publish story previews', 'description_ar' => 'إظهار أو إخفاء زر معاينة القصة في الموقع.', 'description_en' => 'Show or hide Story preview buttons publicly.', 'sort_order' => 73, 'sensitive' => true],
        'booklet_previews.revoke' => ['group_key' => 'orders', 'name_ar' => 'إيقاف روابط المعاينة', 'name_en' => 'Revoke preview links', 'description_ar' => 'إيقاف روابط العملاء وإعادة تفعيلها.', 'description_en' => 'Revoke and re-enable customer preview links.', 'sort_order' => 74, 'sensitive' => true],
        'booklet_previews.delete' => ['group_key' => 'orders', 'name_ar' => 'حذف واستعادة المعاينات', 'name_en' => 'Delete booklet previews', 'description_ar' => 'نقل معاينات الكتب إلى سلة المحذوفات واستعادتها.', 'description_en' => 'Move booklet previews to trash and restore them.', 'sort_order' => 75, 'sensitive' => true],
        'booklet_previews.download_source' => ['group_key' => 'orders', 'name_ar' => 'تنزيل ملفات المعاينة الأصلية', 'name_en' => 'Download preview source PDFs', 'description_ar' => 'تنزيل ملف PDF الأصلي من لوحة الإدارة فقط.', 'description_en' => 'Download original preview PDFs from admin only.', 'sort_order' => 76, 'sensitive' => true],

        'production_studio.view' => ['group_key' => 'production_studio', 'name_ar' => 'عرض استوديو الإنتاج', 'name_en' => 'View Production Studio', 'description_ar' => 'عرض مشاريع استوديو الإنتاج والبيانات المرجعية.', 'description_en' => 'View Production Studio projects and reference data.', 'sort_order' => 10, 'sensitive' => true],
        'production_studio.create_from_order' => ['group_key' => 'production_studio', 'name_ar' => 'إرسال الطلب للاستوديو', 'name_en' => 'Send orders to Studio', 'description_ar' => 'إنشاء مشروع إنتاج معزول مرتبط بطلب موجود.', 'description_en' => 'Create an isolated production project linked to an existing order.', 'sort_order' => 20, 'sensitive' => true],
        'production_studio.manage' => ['group_key' => 'production_studio', 'name_ar' => 'إدارة مشروع الاستوديو', 'name_en' => 'Manage Studio project', 'description_ar' => 'تحديث حالة المشروع والمرحلة والملاحظات العامة.', 'description_en' => 'Update project status, stage, and production notes.', 'sort_order' => 30, 'sensitive' => true],
        'production_studio.assign' => ['group_key' => 'production_studio', 'name_ar' => 'تعيين مسؤول المشروع', 'name_en' => 'Assign Studio project', 'description_ar' => 'تعيين مشروع إنتاج لأحد أعضاء الفريق.', 'description_en' => 'Assign production projects to staff members.', 'sort_order' => 40, 'sensitive' => true],
        'production_studio.story_edit' => ['group_key' => 'production_studio', 'name_ar' => 'تحرير قصة الاستوديو', 'name_en' => 'Edit Studio story', 'description_ar' => 'إنشاء ومراجعة نسخ القصة الخاصة بالمشروع فقط.', 'description_en' => 'Create and review project-specific story versions.', 'sort_order' => 50, 'sensitive' => true],
        'production_studio.character_profile_edit' => ['group_key' => 'production_studio', 'name_ar' => 'تحرير ملف الشخصية', 'name_en' => 'Edit character profile', 'description_ar' => 'تعديل ملف شخصية الطفل داخل الاستوديو.', 'description_en' => 'Edit the project character profile.', 'sort_order' => 60, 'sensitive' => true],
        'production_studio.scene_edit' => ['group_key' => 'production_studio', 'name_ar' => 'تحرير مشاهد الاستوديو', 'name_en' => 'Edit Studio scenes', 'description_ar' => 'إضافة وتحديث مشاهد المشروع وتجهيزات الصور.', 'description_en' => 'Create and update project scenes.', 'sort_order' => 70, 'sensitive' => true],
        'production_studio.qa_review' => ['group_key' => 'production_studio', 'name_ar' => 'مراجعة جودة الاستوديو', 'name_en' => 'Review Studio QA', 'description_ar' => 'تحديث قائمة مراجعة الجودة واعتماد الاستثناءات.', 'description_en' => 'Update QA checklist items and overrides.', 'sort_order' => 80, 'sensitive' => true],
        'production_studio.archive' => ['group_key' => 'production_studio', 'name_ar' => 'أرشفة مشاريع الاستوديو', 'name_en' => 'Archive Studio projects', 'description_ar' => 'أرشفة أو إعادة فتح مشاريع الاستوديو.', 'description_en' => 'Archive or reopen Studio projects.', 'sort_order' => 90, 'sensitive' => true],
        'production_studio.delete_or_cancel' => ['group_key' => 'production_studio', 'name_ar' => 'إلغاء مشاريع الاستوديو', 'name_en' => 'Cancel Studio projects', 'description_ar' => 'إلغاء مشروع استوديو بدون إلغاء الطلب الأصلي.', 'description_en' => 'Cancel Studio projects without cancelling original orders.', 'sort_order' => 100, 'sensitive' => true],
        'production_studio.settings' => ['group_key' => 'production_studio', 'name_ar' => 'إعدادات استوديو الإنتاج', 'name_en' => 'Production Studio settings', 'description_ar' => 'إدارة إعدادات الاستوديو ومزودي الذكاء الاصطناعي مستقبلًا.', 'description_en' => 'Manage Studio settings and future AI providers.', 'sort_order' => 110, 'sensitive' => true],
        'production_studio.ai_generate' => ['group_key' => 'production_studio', 'name_ar' => 'تشغيل توليد الصور', 'name_en' => 'Run AI image generation', 'description_ar' => 'إرسال مهام توليد صور الذكاء الاصطناعي داخل الاستوديو.', 'description_en' => 'Submit AI image generation jobs inside Studio.', 'sort_order' => 120, 'sensitive' => true],
        'production_studio.ai_review' => ['group_key' => 'production_studio', 'name_ar' => 'مراجعة مخرجات الذكاء الاصطناعي', 'name_en' => 'Review AI outputs', 'description_ar' => 'عرض ومراجعة مخرجات توليد الصور داخل الاستوديو.', 'description_en' => 'View and review generated AI image outputs.', 'sort_order' => 130, 'sensitive' => true],
        'production_studio.ai_approve' => ['group_key' => 'production_studio', 'name_ar' => 'اعتماد صور الذكاء الاصطناعي', 'name_en' => 'Approve AI outputs', 'description_ar' => 'اعتماد أو رفض صور الذكاء الاصطناعي النهائية.', 'description_en' => 'Approve or reject generated AI image outputs.', 'sort_order' => 140, 'sensitive' => true],
        'production_studio.ai_retry' => ['group_key' => 'production_studio', 'name_ar' => 'إعادة محاولة توليد الصور', 'name_en' => 'Retry AI generation', 'description_ar' => 'إعادة محاولة توليد الصور بملاحظات جديدة.', 'description_en' => 'Retry AI image generation with updated notes.', 'sort_order' => 150, 'sensitive' => true],
        'production_studio.ai_view_costs' => ['group_key' => 'production_studio', 'name_ar' => 'عرض تكلفة الذكاء الاصطناعي', 'name_en' => 'View AI costs', 'description_ar' => 'عرض تفاصيل التكلفة المقدرة والفعلية لمهام التوليد.', 'description_en' => 'View estimated and actual generation costs.', 'sort_order' => 160, 'sensitive' => true],
        'production_studio.ai_manage_providers' => ['group_key' => 'production_studio', 'name_ar' => 'إدارة مزودي الذكاء الاصطناعي', 'name_en' => 'Manage AI providers', 'description_ar' => 'إدارة إعدادات ومزودي الذكاء الاصطناعي مستقبلًا.', 'description_en' => 'Manage future AI provider settings.', 'sort_order' => 170, 'sensitive' => true],
        'production_studio.layout_manage' => ['group_key' => 'production_studio', 'name_ar' => 'إدارة الإخراج والطباعة', 'name_en' => 'Manage Layout and Print', 'description_ar' => 'تجهيز وتوليد إصدارات Reader PDF وملفات الطباعة والمانيفست.', 'description_en' => 'Prepare and generate Reader PDF, print files, and manifests.', 'sort_order' => 180, 'sensitive' => true],
        'production_studio.layout_download' => ['group_key' => 'production_studio', 'name_ar' => 'تنزيل ملفات الإنتاج', 'name_en' => 'Download Production Files', 'description_ar' => 'تنزيل ملفات PDF والمانيفست الخاصة بالمشروع.', 'description_en' => 'Download private project PDF and manifest files.', 'sort_order' => 190, 'sensitive' => true],
        'production_studio.automation_manage' => ['group_key' => 'production_studio', 'name_ar' => 'إدارة الإنتاج التلقائي', 'name_en' => 'Manage Production Automation', 'description_ar' => 'بدء وإيقاف واستئناف وإلغاء ومراجعة دورة الإنتاج التلقائي داخل الاستوديو.', 'description_en' => 'Start, pause, resume, cancel, and review Studio automation runs.', 'sort_order' => 200, 'sensitive' => true],
        'production_studio.automation_view_costs' => ['group_key' => 'production_studio', 'name_ar' => 'عرض تكاليف الإنتاج التلقائي', 'name_en' => 'View Production Automation Costs', 'description_ar' => 'عرض الحجز والتكلفة الفعلية والتقديرية ومخاطر الفوترة غير المؤكدة لدورات الإنتاج التلقائي.', 'description_en' => 'View reserved, actual, estimated, and unknown billing exposure for automation runs.', 'sort_order' => 210, 'sensitive' => true],
        'production_studio.final_proof_review' => ['group_key' => 'production_studio', 'name_ar' => 'اعتماد المراجعة النهائية', 'name_en' => 'Review Final Proof', 'description_ar' => 'إنشاء واعتماد أو رفض مراجعة الطباعة النهائية للإنتاج التلقائي.', 'description_en' => 'Create, approve, or reject final production proof reviews for automation runs.', 'sort_order' => 220, 'sensitive' => true],

        'customers.view' => [
            'group_key' => 'customers',
            'name_ar' => 'عرض العملاء',
            'name_en' => 'View customers',
            'description_ar' => 'عرض ملفات العملاء والطلبات وتفاصيل الأطفال والنشاط.',
            'description_en' => 'View customer profiles, orders, child details, and activity.',
            'sort_order' => 10,
        ],
        'customers.update' => [
            'group_key' => 'customers',
            'name_ar' => 'تعديل العملاء',
            'name_en' => 'Update customers',
            'description_ar' => 'تعديل بيانات العملاء وإعادة تعيين كلمة المرور عند الحاجة.',
            'description_en' => 'Edit customer details and reset customer passwords where supported.',
            'sort_order' => 20,
        ],

        'stories.view' => ['group_key' => 'stories', 'name_ar' => 'عرض القصص', 'name_en' => 'View stories', 'description_ar' => 'عرض مكتبة القصص.', 'description_en' => 'View story catalog.', 'sort_order' => 10],
        'stories.create' => ['group_key' => 'stories', 'name_ar' => 'إضافة القصص', 'name_en' => 'Create stories', 'description_ar' => 'إنشاء قصص جديدة.', 'description_en' => 'Create new stories.', 'sort_order' => 20],
        'stories.update' => ['group_key' => 'stories', 'name_ar' => 'تعديل القصص', 'name_en' => 'Update stories', 'description_ar' => 'تعديل بيانات القصص.', 'description_en' => 'Update story records.', 'sort_order' => 30],
        'stories.delete' => ['group_key' => 'stories', 'name_ar' => 'حذف القصص', 'name_en' => 'Delete stories', 'description_ar' => 'حذف القصص.', 'description_en' => 'Delete stories.', 'sort_order' => 40, 'sensitive' => true],
        'story_categories.view' => ['group_key' => 'stories', 'name_ar' => 'عرض تصنيفات القصص', 'name_en' => 'View story categories', 'description_ar' => 'عرض تصنيفات القصص.', 'description_en' => 'View story categories.', 'sort_order' => 50],
        'story_categories.create' => ['group_key' => 'stories', 'name_ar' => 'إضافة تصنيفات القصص', 'name_en' => 'Create story categories', 'description_ar' => 'إضافة تصنيفات القصص.', 'description_en' => 'Create story categories.', 'sort_order' => 60],
        'story_categories.delete' => ['group_key' => 'stories', 'name_ar' => 'حذف تصنيفات القصص', 'name_en' => 'Delete story categories', 'description_ar' => 'حذف تصنيفات القصص.', 'description_en' => 'Delete story categories.', 'sort_order' => 70],
        'story_attachments.view' => ['group_key' => 'stories', 'name_ar' => 'تحميل مرفقات القصص', 'name_en' => 'View story attachments', 'description_ar' => 'تحميل الملفات الخاصة بمرفقات القصص.', 'description_en' => 'Download private story attachments.', 'sort_order' => 80, 'sensitive' => true],
        'story_attachments.create' => ['group_key' => 'stories', 'name_ar' => 'رفع مرفقات القصص', 'name_en' => 'Upload story attachments', 'description_ar' => 'رفع ملفات مرفقة للقصص.', 'description_en' => 'Upload story attachments.', 'sort_order' => 90],
        'story_attachments.delete' => ['group_key' => 'stories', 'name_ar' => 'حذف مرفقات القصص', 'name_en' => 'Delete story attachments', 'description_ar' => 'حذف مرفقات القصص.', 'description_en' => 'Delete story attachments.', 'sort_order' => 100],

        'store.categories.view' => ['group_key' => 'store', 'name_ar' => 'عرض تصنيفات المتجر', 'name_en' => 'View store categories', 'description_ar' => 'عرض تصنيفات منتجات المتجر.', 'description_en' => 'View product categories.', 'sort_order' => 10],
        'store.categories.create' => ['group_key' => 'store', 'name_ar' => 'إضافة تصنيفات المتجر', 'name_en' => 'Create store categories', 'description_ar' => 'إضافة تصنيفات منتجات.', 'description_en' => 'Create product categories.', 'sort_order' => 20],
        'store.categories.update' => ['group_key' => 'store', 'name_ar' => 'تعديل تصنيفات المتجر', 'name_en' => 'Update store categories', 'description_ar' => 'تعديل تصنيفات المنتجات.', 'description_en' => 'Update product categories.', 'sort_order' => 30],
        'store.categories.delete' => ['group_key' => 'store', 'name_ar' => 'حذف تصنيفات المتجر', 'name_en' => 'Delete store categories', 'description_ar' => 'حذف تصنيفات المنتجات.', 'description_en' => 'Delete product categories.', 'sort_order' => 40],
        'store.products.view' => ['group_key' => 'store', 'name_ar' => 'عرض المنتجات', 'name_en' => 'View products', 'description_ar' => 'عرض منتجات المتجر.', 'description_en' => 'View products.', 'sort_order' => 50],
        'store.products.create' => ['group_key' => 'store', 'name_ar' => 'إضافة المنتجات', 'name_en' => 'Create products', 'description_ar' => 'إضافة منتجات جديدة.', 'description_en' => 'Create products.', 'sort_order' => 60],
        'store.products.update' => ['group_key' => 'store', 'name_ar' => 'تعديل المنتجات', 'name_en' => 'Update products', 'description_ar' => 'تعديل منتجات المتجر.', 'description_en' => 'Update products.', 'sort_order' => 70],
        'store.products.delete' => ['group_key' => 'store', 'name_ar' => 'حذف المنتجات', 'name_en' => 'Delete products', 'description_ar' => 'حذف منتجات المتجر.', 'description_en' => 'Delete products.', 'sort_order' => 80],
        'store.variants.create' => ['group_key' => 'store', 'name_ar' => 'إضافة متغيرات المنتجات', 'name_en' => 'Create variants', 'description_ar' => 'إضافة متغيرات للمنتجات.', 'description_en' => 'Create product variants.', 'sort_order' => 90],
        'store.variants.update' => ['group_key' => 'store', 'name_ar' => 'تعديل متغيرات المنتجات', 'name_en' => 'Update variants', 'description_ar' => 'تعديل متغيرات المنتجات.', 'description_en' => 'Update product variants.', 'sort_order' => 100],
        'store.variants.delete' => ['group_key' => 'store', 'name_ar' => 'حذف متغيرات المنتجات', 'name_en' => 'Delete variants', 'description_ar' => 'حذف متغيرات المنتجات.', 'description_en' => 'Delete product variants.', 'sort_order' => 110],
        'store.homepage_sections.view' => ['group_key' => 'store', 'name_ar' => 'عرض أقسام المتجر في الرئيسية', 'name_en' => 'View homepage store sections', 'description_ar' => 'عرض أقسام منتجات الصفحة الرئيسية.', 'description_en' => 'View homepage store sections.', 'sort_order' => 120],
        'store.homepage_sections.create' => ['group_key' => 'store', 'name_ar' => 'إضافة أقسام المتجر في الرئيسية', 'name_en' => 'Create homepage store sections', 'description_ar' => 'إضافة أقسام للصفحة الرئيسية.', 'description_en' => 'Create homepage store sections.', 'sort_order' => 130],
        'store.homepage_sections.update' => ['group_key' => 'store', 'name_ar' => 'تعديل أقسام المتجر في الرئيسية', 'name_en' => 'Update homepage store sections', 'description_ar' => 'تعديل أقسام الصفحة الرئيسية.', 'description_en' => 'Update homepage store sections.', 'sort_order' => 140],
        'store.homepage_sections.delete' => ['group_key' => 'store', 'name_ar' => 'حذف أقسام المتجر في الرئيسية', 'name_en' => 'Delete homepage store sections', 'description_ar' => 'حذف أقسام الصفحة الرئيسية.', 'description_en' => 'Delete homepage store sections.', 'sort_order' => 150],
        'store.upsell_rules.view' => ['group_key' => 'store', 'name_ar' => 'عرض قواعد الترشيح', 'name_en' => 'View upsell rules', 'description_ar' => 'عرض قواعد ترشيح المنتجات.', 'description_en' => 'View upsell rules.', 'sort_order' => 160],
        'store.upsell_rules.create' => ['group_key' => 'store', 'name_ar' => 'إضافة قواعد الترشيح', 'name_en' => 'Create upsell rules', 'description_ar' => 'إضافة قواعد ترشيح المنتجات.', 'description_en' => 'Create upsell rules.', 'sort_order' => 170],
        'store.upsell_rules.update' => ['group_key' => 'store', 'name_ar' => 'تعديل قواعد الترشيح', 'name_en' => 'Update upsell rules', 'description_ar' => 'تعديل قواعد ترشيح المنتجات.', 'description_en' => 'Update upsell rules.', 'sort_order' => 180],
        'store.upsell_rules.delete' => ['group_key' => 'store', 'name_ar' => 'حذف قواعد الترشيح', 'name_en' => 'Delete upsell rules', 'description_ar' => 'حذف قواعد ترشيح المنتجات.', 'description_en' => 'Delete upsell rules.', 'sort_order' => 190],

        'content.faqs.view' => ['group_key' => 'content', 'name_ar' => 'عرض الأسئلة الشائعة', 'name_en' => 'View FAQs', 'description_ar' => 'عرض الأسئلة الشائعة.', 'description_en' => 'View FAQs.', 'sort_order' => 10],
        'content.faqs.create' => ['group_key' => 'content', 'name_ar' => 'إضافة الأسئلة الشائعة', 'name_en' => 'Create FAQs', 'description_ar' => 'إضافة أسئلة شائعة.', 'description_en' => 'Create FAQs.', 'sort_order' => 20],
        'content.faqs.update' => ['group_key' => 'content', 'name_ar' => 'تعديل الأسئلة الشائعة', 'name_en' => 'Update FAQs', 'description_ar' => 'تعديل الأسئلة الشائعة.', 'description_en' => 'Update FAQs.', 'sort_order' => 30],
        'content.faqs.delete' => ['group_key' => 'content', 'name_ar' => 'حذف الأسئلة الشائعة', 'name_en' => 'Delete FAQs', 'description_ar' => 'حذف الأسئلة الشائعة.', 'description_en' => 'Delete FAQs.', 'sort_order' => 40],
        'content.testimonials.view' => ['group_key' => 'content', 'name_ar' => 'عرض آراء العملاء', 'name_en' => 'View testimonials', 'description_ar' => 'عرض آراء العملاء.', 'description_en' => 'View testimonials.', 'sort_order' => 50],
        'content.testimonials.create' => ['group_key' => 'content', 'name_ar' => 'إضافة آراء العملاء', 'name_en' => 'Create testimonials', 'description_ar' => 'إضافة آراء العملاء.', 'description_en' => 'Create testimonials.', 'sort_order' => 60],
        'content.testimonials.update' => ['group_key' => 'content', 'name_ar' => 'تعديل آراء العملاء', 'name_en' => 'Update testimonials', 'description_ar' => 'تعديل آراء العملاء.', 'description_en' => 'Update testimonials.', 'sort_order' => 70],
        'content.testimonials.delete' => ['group_key' => 'content', 'name_ar' => 'حذف آراء العملاء', 'name_en' => 'Delete testimonials', 'description_ar' => 'حذف آراء العملاء.', 'description_en' => 'Delete testimonials.', 'sort_order' => 80],
        'content.messages.view' => ['group_key' => 'content', 'name_ar' => 'عرض الرسائل الواردة', 'name_en' => 'View messages', 'description_ar' => 'عرض الرسائل الواردة.', 'description_en' => 'View contact messages.', 'sort_order' => 90],
        'content.messages.delete' => ['group_key' => 'content', 'name_ar' => 'حذف الرسائل الواردة', 'name_en' => 'Delete messages', 'description_ar' => 'حذف الرسائل الواردة.', 'description_en' => 'Delete contact messages.', 'sort_order' => 100],

        'settings.site.view' => ['group_key' => 'settings', 'name_ar' => 'عرض إعدادات الموقع', 'name_en' => 'View site settings', 'description_ar' => 'عرض إعدادات الموقع العامة.', 'description_en' => 'View site settings.', 'sort_order' => 10],
        'settings.site.update' => ['group_key' => 'settings', 'name_ar' => 'تحديث إعدادات الموقع', 'name_en' => 'Update site settings', 'description_ar' => 'تحديث إعدادات الموقع العامة.', 'description_en' => 'Update site settings.', 'sort_order' => 20, 'sensitive' => true],
        'settings.production_prompt.view' => ['group_key' => 'settings', 'name_ar' => 'عرض قالب برومبت الإنتاج', 'name_en' => 'View production prompt template', 'description_ar' => 'عرض صفحة قالب برومبت الإنتاج العام.', 'description_en' => 'View global production prompt template page.', 'sort_order' => 30, 'sensitive' => true],
        'settings.production_prompt.manage' => ['group_key' => 'settings', 'name_ar' => 'إدارة قالب برومبت الإنتاج', 'name_en' => 'Manage production prompt template', 'description_ar' => 'حفظ ومعاينة واستعادة قالب برومبت الإنتاج العام.', 'description_en' => 'Save, preview, reset, and change global production prompt template.', 'sort_order' => 40, 'sensitive' => true],
        'settings.delivery_zones.view' => ['group_key' => 'settings', 'name_ar' => 'عرض مناطق التوصيل', 'name_en' => 'View delivery zones', 'description_ar' => 'عرض الدول والمحافظات ومصاريف التوصيل.', 'description_en' => 'View delivery zones.', 'sort_order' => 50],
        'settings.delivery_zones.create' => ['group_key' => 'settings', 'name_ar' => 'إضافة مناطق التوصيل', 'name_en' => 'Create delivery zones', 'description_ar' => 'إضافة دول أو محافظات للتوصيل.', 'description_en' => 'Create delivery zones.', 'sort_order' => 60],
        'settings.delivery_zones.update' => ['group_key' => 'settings', 'name_ar' => 'تعديل مناطق التوصيل', 'name_en' => 'Update delivery zones', 'description_ar' => 'تعديل الدول أو المحافظات ومصاريفها.', 'description_en' => 'Update delivery zones.', 'sort_order' => 70],
        'settings.delivery_zones.delete' => ['group_key' => 'settings', 'name_ar' => 'حذف مناطق التوصيل', 'name_en' => 'Delete delivery zones', 'description_ar' => 'حذف دول أو محافظات التوصيل.', 'description_en' => 'Delete delivery zones.', 'sort_order' => 80],
        'settings.pricing.view' => ['group_key' => 'settings', 'name_ar' => 'عرض باقات الأسعار', 'name_en' => 'View pricing packages', 'description_ar' => 'عرض باقات الأسعار.', 'description_en' => 'View pricing packages.', 'sort_order' => 90],
        'settings.pricing.create' => ['group_key' => 'settings', 'name_ar' => 'إضافة باقات الأسعار', 'name_en' => 'Create pricing packages', 'description_ar' => 'إضافة باقات أسعار.', 'description_en' => 'Create pricing packages.', 'sort_order' => 100],
        'settings.pricing.update' => ['group_key' => 'settings', 'name_ar' => 'تعديل باقات الأسعار', 'name_en' => 'Update pricing packages', 'description_ar' => 'تعديل باقات الأسعار.', 'description_en' => 'Update pricing packages.', 'sort_order' => 110],
        'settings.pricing.delete' => ['group_key' => 'settings', 'name_ar' => 'حذف باقات الأسعار', 'name_en' => 'Delete pricing packages', 'description_ar' => 'حذف باقات الأسعار.', 'description_en' => 'Delete pricing packages.', 'sort_order' => 120],
        'settings.ai_providers.view' => ['group_key' => 'settings', 'name_ar' => 'عرض مزودي الذكاء الاصطناعي', 'name_en' => 'View AI providers', 'description_ar' => 'عرض إعدادات مزودي ونماذج الذكاء الاصطناعي.', 'description_en' => 'View AI provider and model settings.', 'sort_order' => 130, 'sensitive' => true],
        'settings.ai_providers.manage' => ['group_key' => 'settings', 'name_ar' => 'إدارة إعدادات مزودي الذكاء الاصطناعي', 'name_en' => 'Manage AI providers', 'description_ar' => 'تحديث إعدادات مزود الذكاء الاصطناعي الآمنة.', 'description_en' => 'Update safe AI provider settings.', 'sort_order' => 140, 'sensitive' => true],
        'settings.ai_providers.manage_credentials' => ['group_key' => 'settings', 'name_ar' => 'إدارة مفاتيح مزودي الذكاء الاصطناعي', 'name_en' => 'Manage AI credentials', 'description_ar' => 'حفظ أو استبدال أو حذف مفاتيح API المشفرة.', 'description_en' => 'Save, replace, or remove encrypted provider API keys.', 'sort_order' => 150, 'sensitive' => true],
        'settings.ai_providers.manage_models' => ['group_key' => 'settings', 'name_ar' => 'إدارة نماذج الذكاء الاصطناعي', 'name_en' => 'Manage AI models', 'description_ar' => 'تفعيل النماذج وتحديد الافتراضيات والتكلفة التقديرية.', 'description_en' => 'Activate models, defaults, and estimated costs.', 'sort_order' => 160, 'sensitive' => true],
        'settings.ai_providers.test_connection' => ['group_key' => 'settings', 'name_ar' => 'اختبار اتصال مزودي الذكاء الاصطناعي', 'name_en' => 'Test AI provider connection', 'description_ar' => 'تشغيل اختبار اتصال آمن من الخادم.', 'description_en' => 'Run safe server-side provider connection tests.', 'sort_order' => 170, 'sensitive' => true],
        'settings.ai_providers.enable_disable' => ['group_key' => 'settings', 'name_ar' => 'تفعيل أو إيقاف مزودي الذكاء الاصطناعي', 'name_en' => 'Enable or disable AI providers', 'description_ar' => 'تفعيل أو إيقاف المزودين والنماذج.', 'description_en' => 'Enable or disable providers and models.', 'sort_order' => 180, 'sensitive' => true],
        'settings.ai_providers.view_costs' => ['group_key' => 'settings', 'name_ar' => 'عرض تكاليف الذكاء الاصطناعي', 'name_en' => 'View AI provider costs', 'description_ar' => 'عرض وتعديل التكلفة التقديرية للنماذج.', 'description_en' => 'View and edit estimated model costs.', 'sort_order' => 190, 'sensitive' => true],
        'settings.notifications.view' => ['group_key' => 'settings', 'name_ar' => 'عرض مركز التنبيهات', 'name_en' => 'View Notification Center', 'description_ar' => 'عرض إعدادات وقنوات وسجلات تنبيهات الإدارة.', 'description_en' => 'View admin notification channels, rules, and delivery logs.', 'sort_order' => 200, 'sensitive' => true],
        'settings.notifications.manage' => ['group_key' => 'settings', 'name_ar' => 'إدارة مركز التنبيهات', 'name_en' => 'Manage Notification Center', 'description_ar' => 'تحديث إعدادات قنوات التنبيهات العامة والحدود التشغيلية.', 'description_en' => 'Update notification channel settings and operational thresholds.', 'sort_order' => 210, 'sensitive' => true],
        'settings.notifications.manage_credentials' => ['group_key' => 'settings', 'name_ar' => 'إدارة بيانات اعتماد التنبيهات', 'name_en' => 'Manage notification credentials', 'description_ar' => 'حفظ أو استبدال أو حذف توكنات قنوات التنبيه المشفرة.', 'description_en' => 'Save, replace, or remove encrypted notification channel credentials.', 'sort_order' => 220, 'sensitive' => true],
        'settings.notifications.test' => ['group_key' => 'settings', 'name_ar' => 'اختبار التنبيهات', 'name_en' => 'Test notifications', 'description_ar' => 'إرسال رسائل اختبار من الخادم لقنوات التنبيه.', 'description_en' => 'Send server-side test messages for notification channels.', 'sort_order' => 230, 'sensitive' => true],
        'settings.notifications.view_logs' => ['group_key' => 'settings', 'name_ar' => 'عرض سجل تسليم التنبيهات', 'name_en' => 'View notification logs', 'description_ar' => 'عرض سجل التسليم الآمن والتنبيهات الفاشلة.', 'description_en' => 'View safe delivery history and failed notifications.', 'sort_order' => 240, 'sensitive' => true],
        'settings.notifications.manage_rules' => ['group_key' => 'settings', 'name_ar' => 'إدارة قواعد التنبيهات', 'name_en' => 'Manage notification rules', 'description_ar' => 'تفعيل أو تعطيل التنبيهات لكل حدث وقناة.', 'description_en' => 'Enable or disable notifications per event and channel.', 'sort_order' => 250, 'sensitive' => true],
        'settings.mobile.view' => ['group_key' => 'settings', 'name_ar' => 'عرض تشغيل تطبيق الهاتف', 'name_en' => 'View mobile operations', 'description_ar' => 'عرض إعدادات التطبيق والتحليلات والطلبات المتعلقة بالخصوصية.', 'description_en' => 'View app configuration, analytics, and privacy operations.', 'sort_order' => 260, 'sensitive' => true],
        'settings.mobile.manage' => ['group_key' => 'settings', 'name_ar' => 'إدارة تشغيل تطبيق الهاتف', 'name_en' => 'Manage mobile operations', 'description_ar' => 'تحديث إعدادات الإصدار والعروض وحالات طلبات الخصوصية.', 'description_en' => 'Manage app versions, promotions, and privacy request workflow.', 'sort_order' => 270, 'sensitive' => true],

        'admin_users.view' => ['group_key' => 'admin_users', 'name_ar' => 'عرض المشرفين', 'name_en' => 'View admin users', 'description_ar' => 'عرض قائمة حسابات المشرفين.', 'description_en' => 'View staff accounts.', 'sort_order' => 10, 'sensitive' => true],
        'admin_users.create' => ['group_key' => 'admin_users', 'name_ar' => 'إضافة مشرفين', 'name_en' => 'Create admin users', 'description_ar' => 'إنشاء حسابات مشرفين جديدة.', 'description_en' => 'Create new staff accounts.', 'sort_order' => 20, 'sensitive' => true],
        'admin_users.update' => ['group_key' => 'admin_users', 'name_ar' => 'تعديل المشرفين', 'name_en' => 'Update admin users', 'description_ar' => 'تعديل بيانات حسابات المشرفين.', 'description_en' => 'Update staff account details.', 'sort_order' => 30, 'sensitive' => true],
        'admin_users.delete' => ['group_key' => 'admin_users', 'name_ar' => 'حذف المشرفين', 'name_en' => 'Delete admin users', 'description_ar' => 'حذف حسابات المشرفين.', 'description_en' => 'Delete staff accounts.', 'sort_order' => 40, 'sensitive' => true],
        'admin_users.permissions.manage' => ['group_key' => 'admin_users', 'name_ar' => 'إدارة صلاحيات المشرفين', 'name_en' => 'Manage admin permissions', 'description_ar' => 'تعيين أو سحب الصلاحيات وتفعيل أو إيقاف حسابات المشرفين.', 'description_en' => 'Assign or revoke staff permissions and activate/deactivate staff accounts.', 'sort_order' => 50, 'sensitive' => true],

        'activity_logs.view' => ['group_key' => 'activity_logs', 'name_ar' => 'عرض سجل النشاط', 'name_en' => 'View activity logs', 'description_ar' => 'عرض سجل نشاط لوحة الإدارة.', 'description_en' => 'View admin activity logs.', 'sort_order' => 10, 'sensitive' => true],
    ],
];
