<?php

return [
    'last_manager_error' => 'لا يمكن تنفيذ العملية لأن النظام يجب أن يحتفظ بمستخدم إداري نشط واحد على الأقل قادر على إدارة الصلاحيات.',

    'groups' => [
        'dashboard' => [
            'name_ar' => 'لوحة القيادة',
            'name_en' => 'Dashboard',
            'sort_order' => 10,
        ],
        'orders' => [
            'name_ar' => 'الطلبات والإنتاج',
            'name_en' => 'Orders and Production',
            'sort_order' => 20,
        ],
        'customers' => [
            'name_ar' => 'العملاء',
            'name_en' => 'Customers',
            'sort_order' => 30,
        ],
        'stories' => [
            'name_ar' => 'القصص',
            'name_en' => 'Stories',
            'sort_order' => 40,
        ],
        'store' => [
            'name_ar' => 'المتجر والمنتجات',
            'name_en' => 'Store and Products',
            'sort_order' => 50,
        ],
        'content' => [
            'name_ar' => 'إدارة المحتوى',
            'name_en' => 'Content',
            'sort_order' => 60,
        ],
        'settings' => [
            'name_ar' => 'الإعدادات والتشغيل',
            'name_en' => 'Settings and Operations',
            'sort_order' => 70,
        ],
        'admin_users' => [
            'name_ar' => 'إدارة المستخدمين والصلاحيات',
            'name_en' => 'Admin Users and Permissions',
            'sort_order' => 80,
        ],
        'activity_logs' => [
            'name_ar' => 'سجل النشاط',
            'name_en' => 'Activity Logs',
            'sort_order' => 90,
        ],
    ],

    'permissions' => [
        'dashboard.view' => [
            'group_key' => 'dashboard',
            'name_ar' => 'عرض لوحة القيادة',
            'name_en' => 'View dashboard',
            'description_ar' => 'عرض صفحة لوحة القيادة والإحصاءات العامة.',
            'description_en' => 'View dashboard and overview metrics.',
            'sort_order' => 10,
        ],

        'orders.view' => [
            'group_key' => 'orders',
            'name_ar' => 'عرض الطلبات',
            'name_en' => 'View orders',
            'description_ar' => 'عرض قائمة الطلبات وتفاصيل الطلب.',
            'description_en' => 'View order list and order details.',
            'sort_order' => 10,
        ],
        'orders.update' => [
            'group_key' => 'orders',
            'name_ar' => 'تحديث الطلبات',
            'name_en' => 'Update orders',
            'description_ar' => 'تحديث حالة الطلب والملاحظات وبيانات التشغيل.',
            'description_en' => 'Update order status, notes, and operational fields.',
            'sort_order' => 20,
        ],
        'orders.preview.upload' => [
            'group_key' => 'orders',
            'name_ar' => 'رفع معاينات التصميم',
            'name_en' => 'Upload previews',
            'description_ar' => 'رفع أو إدارة تصميمات المعاينة الخاصة بالعميل.',
            'description_en' => 'Upload or manage customer design previews.',
            'sort_order' => 30,
        ],
        'orders.photos.view' => [
            'group_key' => 'orders',
            'name_ar' => 'عرض صور الأطفال',
            'name_en' => 'View child photos',
            'description_ar' => 'عرض صور الأطفال وروابط الإنتاج الخاصة بها.',
            'description_en' => 'View child photos and secure production photo links.',
            'sort_order' => 40,
            'sensitive' => true,
        ],
        'orders.production_prompt.manage' => [
            'group_key' => 'orders',
            'name_ar' => 'إدارة برومبت إنتاج الطلب',
            'name_en' => 'Manage order production prompt',
            'description_ar' => 'عرض وتوليد وتعديل وحفظ نسخ برومبت الإنتاج للطلبات.',
            'description_en' => 'View, regenerate, edit, override, reset, and snapshot order production prompts.',
            'sort_order' => 50,
            'sensitive' => true,
        ],

        'customers.view' => [
            'group_key' => 'customers',
            'name_ar' => 'عرض العملاء',
            'name_en' => 'View customers',
            'description_ar' => 'عرض ملفات العملاء والطلبات وتفاصيل الأطفال والنشاط.',
            'description_en' => 'View customer profiles, orders, child details, and activity.',
            'sort_order' => 10,
        ],
        'customers.update' => [
            'group_key' => 'customers',
            'name_ar' => 'تعديل العملاء',
            'name_en' => 'Update customers',
            'description_ar' => 'تعديل بيانات العملاء وإعادة تعيين كلمة المرور عند الحاجة.',
            'description_en' => 'Edit customer details and reset customer passwords where supported.',
            'sort_order' => 20,
        ],

        'stories.view' => ['group_key' => 'stories', 'name_ar' => 'عرض القصص', 'name_en' => 'View stories', 'description_ar' => 'عرض مكتبة القصص.', 'description_en' => 'View story catalog.', 'sort_order' => 10],
        'stories.create' => ['group_key' => 'stories', 'name_ar' => 'إضافة القصص', 'name_en' => 'Create stories', 'description_ar' => 'إنشاء قصص جديدة.', 'description_en' => 'Create new stories.', 'sort_order' => 20],
        'stories.update' => ['group_key' => 'stories', 'name_ar' => 'تعديل القصص', 'name_en' => 'Update stories', 'description_ar' => 'تعديل بيانات القصص.', 'description_en' => 'Update story records.', 'sort_order' => 30],
        'stories.delete' => ['group_key' => 'stories', 'name_ar' => 'حذف القصص', 'name_en' => 'Delete stories', 'description_ar' => 'حذف القصص.', 'description_en' => 'Delete stories.', 'sort_order' => 40, 'sensitive' => true],
        'story_categories.view' => ['group_key' => 'stories', 'name_ar' => 'عرض تصنيفات القصص', 'name_en' => 'View story categories', 'description_ar' => 'عرض تصنيفات القصص.', 'description_en' => 'View story categories.', 'sort_order' => 50],
        'story_categories.create' => ['group_key' => 'stories', 'name_ar' => 'إضافة تصنيفات القصص', 'name_en' => 'Create story categories', 'description_ar' => 'إضافة تصنيفات القصص.', 'description_en' => 'Create story categories.', 'sort_order' => 60],
        'story_categories.delete' => ['group_key' => 'stories', 'name_ar' => 'حذف تصنيفات القصص', 'name_en' => 'Delete story categories', 'description_ar' => 'حذف تصنيفات القصص.', 'description_en' => 'Delete story categories.', 'sort_order' => 70],
        'story_attachments.view' => ['group_key' => 'stories', 'name_ar' => 'تحميل مرفقات القصص', 'name_en' => 'View story attachments', 'description_ar' => 'تحميل الملفات الخاصة بمرفقات القصص.', 'description_en' => 'Download private story attachments.', 'sort_order' => 80, 'sensitive' => true],
        'story_attachments.create' => ['group_key' => 'stories', 'name_ar' => 'رفع مرفقات القصص', 'name_en' => 'Upload story attachments', 'description_ar' => 'رفع ملفات مرفقة للقصص.', 'description_en' => 'Upload story attachments.', 'sort_order' => 90],
        'story_attachments.delete' => ['group_key' => 'stories', 'name_ar' => 'حذف مرفقات القصص', 'name_en' => 'Delete story attachments', 'description_ar' => 'حذف مرفقات القصص.', 'description_en' => 'Delete story attachments.', 'sort_order' => 100],

        'store.categories.view' => ['group_key' => 'store', 'name_ar' => 'عرض تصنيفات المتجر', 'name_en' => 'View store categories', 'description_ar' => 'عرض تصنيفات منتجات المتجر.', 'description_en' => 'View product categories.', 'sort_order' => 10],
        'store.categories.create' => ['group_key' => 'store', 'name_ar' => 'إضافة تصنيفات المتجر', 'name_en' => 'Create store categories', 'description_ar' => 'إضافة تصنيفات منتجات.', 'description_en' => 'Create product categories.', 'sort_order' => 20],
        'store.categories.update' => ['group_key' => 'store', 'name_ar' => 'تعديل تصنيفات المتجر', 'name_en' => 'Update store categories', 'description_ar' => 'تعديل تصنيفات المنتجات.', 'description_en' => 'Update product categories.', 'sort_order' => 30],
        'store.categories.delete' => ['group_key' => 'store', 'name_ar' => 'حذف تصنيفات المتجر', 'name_en' => 'Delete store categories', 'description_ar' => 'حذف تصنيفات المنتجات.', 'description_en' => 'Delete product categories.', 'sort_order' => 40],
        'store.products.view' => ['group_key' => 'store', 'name_ar' => 'عرض المنتجات', 'name_en' => 'View products', 'description_ar' => 'عرض منتجات المتجر.', 'description_en' => 'View products.', 'sort_order' => 50],
        'store.products.create' => ['group_key' => 'store', 'name_ar' => 'إضافة المنتجات', 'name_en' => 'Create products', 'description_ar' => 'إضافة منتجات جديدة.', 'description_en' => 'Create products.', 'sort_order' => 60],
        'store.products.update' => ['group_key' => 'store', 'name_ar' => 'تعديل المنتجات', 'name_en' => 'Update products', 'description_ar' => 'تعديل منتجات المتجر.', 'description_en' => 'Update products.', 'sort_order' => 70],
        'store.products.delete' => ['group_key' => 'store', 'name_ar' => 'حذف المنتجات', 'name_en' => 'Delete products', 'description_ar' => 'حذف منتجات المتجر.', 'description_en' => 'Delete products.', 'sort_order' => 80],
        'store.variants.create' => ['group_key' => 'store', 'name_ar' => 'إضافة متغيرات المنتجات', 'name_en' => 'Create variants', 'description_ar' => 'إضافة متغيرات للمنتجات.', 'description_en' => 'Create product variants.', 'sort_order' => 90],
        'store.variants.update' => ['group_key' => 'store', 'name_ar' => 'تعديل متغيرات المنتجات', 'name_en' => 'Update variants', 'description_ar' => 'تعديل متغيرات المنتجات.', 'description_en' => 'Update product variants.', 'sort_order' => 100],
        'store.variants.delete' => ['group_key' => 'store', 'name_ar' => 'حذف متغيرات المنتجات', 'name_en' => 'Delete variants', 'description_ar' => 'حذف متغيرات المنتجات.', 'description_en' => 'Delete product variants.', 'sort_order' => 110],
        'store.homepage_sections.view' => ['group_key' => 'store', 'name_ar' => 'عرض أقسام المتجر في الرئيسية', 'name_en' => 'View homepage store sections', 'description_ar' => 'عرض أقسام منتجات الصفحة الرئيسية.', 'description_en' => 'View homepage store sections.', 'sort_order' => 120],
        'store.homepage_sections.create' => ['group_key' => 'store', 'name_ar' => 'إضافة أقسام المتجر في الرئيسية', 'name_en' => 'Create homepage store sections', 'description_ar' => 'إضافة أقسام للصفحة الرئيسية.', 'description_en' => 'Create homepage store sections.', 'sort_order' => 130],
        'store.homepage_sections.update' => ['group_key' => 'store', 'name_ar' => 'تعديل أقسام المتجر في الرئيسية', 'name_en' => 'Update homepage store sections', 'description_ar' => 'تعديل أقسام الصفحة الرئيسية.', 'description_en' => 'Update homepage store sections.', 'sort_order' => 140],
        'store.homepage_sections.delete' => ['group_key' => 'store', 'name_ar' => 'حذف أقسام المتجر في الرئيسية', 'name_en' => 'Delete homepage store sections', 'description_ar' => 'حذف أقسام الصفحة الرئيسية.', 'description_en' => 'Delete homepage store sections.', 'sort_order' => 150],
        'store.upsell_rules.view' => ['group_key' => 'store', 'name_ar' => 'عرض قواعد الترشيح', 'name_en' => 'View upsell rules', 'description_ar' => 'عرض قواعد ترشيح المنتجات.', 'description_en' => 'View upsell rules.', 'sort_order' => 160],
        'store.upsell_rules.create' => ['group_key' => 'store', 'name_ar' => 'إضافة قواعد الترشيح', 'name_en' => 'Create upsell rules', 'description_ar' => 'إضافة قواعد ترشيح المنتجات.', 'description_en' => 'Create upsell rules.', 'sort_order' => 170],
        'store.upsell_rules.update' => ['group_key' => 'store', 'name_ar' => 'تعديل قواعد الترشيح', 'name_en' => 'Update upsell rules', 'description_ar' => 'تعديل قواعد ترشيح المنتجات.', 'description_en' => 'Update upsell rules.', 'sort_order' => 180],
        'store.upsell_rules.delete' => ['group_key' => 'store', 'name_ar' => 'حذف قواعد الترشيح', 'name_en' => 'Delete upsell rules', 'description_ar' => 'حذف قواعد ترشيح المنتجات.', 'description_en' => 'Delete upsell rules.', 'sort_order' => 190],

        'content.faqs.view' => ['group_key' => 'content', 'name_ar' => 'عرض الأسئلة الشائعة', 'name_en' => 'View FAQs', 'description_ar' => 'عرض الأسئلة الشائعة.', 'description_en' => 'View FAQs.', 'sort_order' => 10],
        'content.faqs.create' => ['group_key' => 'content', 'name_ar' => 'إضافة الأسئلة الشائعة', 'name_en' => 'Create FAQs', 'description_ar' => 'إضافة أسئلة شائعة.', 'description_en' => 'Create FAQs.', 'sort_order' => 20],
        'content.faqs.update' => ['group_key' => 'content', 'name_ar' => 'تعديل الأسئلة الشائعة', 'name_en' => 'Update FAQs', 'description_ar' => 'تعديل الأسئلة الشائعة.', 'description_en' => 'Update FAQs.', 'sort_order' => 30],
        'content.faqs.delete' => ['group_key' => 'content', 'name_ar' => 'حذف الأسئلة الشائعة', 'name_en' => 'Delete FAQs', 'description_ar' => 'حذف الأسئلة الشائعة.', 'description_en' => 'Delete FAQs.', 'sort_order' => 40],
        'content.testimonials.view' => ['group_key' => 'content', 'name_ar' => 'عرض آراء العملاء', 'name_en' => 'View testimonials', 'description_ar' => 'عرض آراء العملاء.', 'description_en' => 'View testimonials.', 'sort_order' => 50],
        'content.testimonials.create' => ['group_key' => 'content', 'name_ar' => 'إضافة آراء العملاء', 'name_en' => 'Create testimonials', 'description_ar' => 'إضافة آراء العملاء.', 'description_en' => 'Create testimonials.', 'sort_order' => 60],
        'content.testimonials.update' => ['group_key' => 'content', 'name_ar' => 'تعديل آراء العملاء', 'name_en' => 'Update testimonials', 'description_ar' => 'تعديل آراء العملاء.', 'description_en' => 'Update testimonials.', 'sort_order' => 70],
        'content.testimonials.delete' => ['group_key' => 'content', 'name_ar' => 'حذف آراء العملاء', 'name_en' => 'Delete testimonials', 'description_ar' => 'حذف آراء العملاء.', 'description_en' => 'Delete testimonials.', 'sort_order' => 80],
        'content.messages.view' => ['group_key' => 'content', 'name_ar' => 'عرض الرسائل الواردة', 'name_en' => 'View messages', 'description_ar' => 'عرض الرسائل الواردة.', 'description_en' => 'View contact messages.', 'sort_order' => 90],
        'content.messages.delete' => ['group_key' => 'content', 'name_ar' => 'حذف الرسائل الواردة', 'name_en' => 'Delete messages', 'description_ar' => 'حذف الرسائل الواردة.', 'description_en' => 'Delete contact messages.', 'sort_order' => 100],

        'settings.site.view' => ['group_key' => 'settings', 'name_ar' => 'عرض إعدادات الموقع', 'name_en' => 'View site settings', 'description_ar' => 'عرض إعدادات الموقع العامة.', 'description_en' => 'View site settings.', 'sort_order' => 10],
        'settings.site.update' => ['group_key' => 'settings', 'name_ar' => 'تحديث إعدادات الموقع', 'name_en' => 'Update site settings', 'description_ar' => 'تحديث إعدادات الموقع العامة.', 'description_en' => 'Update site settings.', 'sort_order' => 20, 'sensitive' => true],
        'settings.production_prompt.view' => ['group_key' => 'settings', 'name_ar' => 'عرض قالب برومبت الإنتاج', 'name_en' => 'View production prompt template', 'description_ar' => 'عرض صفحة قالب برومبت الإنتاج العام.', 'description_en' => 'View global production prompt template page.', 'sort_order' => 30, 'sensitive' => true],
        'settings.production_prompt.manage' => ['group_key' => 'settings', 'name_ar' => 'إدارة قالب برومبت الإنتاج', 'name_en' => 'Manage production prompt template', 'description_ar' => 'حفظ ومعاينة واستعادة قالب برومبت الإنتاج العام.', 'description_en' => 'Save, preview, reset, and change global production prompt template.', 'sort_order' => 40, 'sensitive' => true],
        'settings.delivery_zones.view' => ['group_key' => 'settings', 'name_ar' => 'عرض مناطق التوصيل', 'name_en' => 'View delivery zones', 'description_ar' => 'عرض الدول والمحافظات ومصاريف التوصيل.', 'description_en' => 'View delivery zones.', 'sort_order' => 50],
        'settings.delivery_zones.create' => ['group_key' => 'settings', 'name_ar' => 'إضافة مناطق التوصيل', 'name_en' => 'Create delivery zones', 'description_ar' => 'إضافة دول أو محافظات للتوصيل.', 'description_en' => 'Create delivery zones.', 'sort_order' => 60],
        'settings.delivery_zones.update' => ['group_key' => 'settings', 'name_ar' => 'تعديل مناطق التوصيل', 'name_en' => 'Update delivery zones', 'description_ar' => 'تعديل الدول أو المحافظات ومصاريفها.', 'description_en' => 'Update delivery zones.', 'sort_order' => 70],
        'settings.delivery_zones.delete' => ['group_key' => 'settings', 'name_ar' => 'حذف مناطق التوصيل', 'name_en' => 'Delete delivery zones', 'description_ar' => 'حذف دول أو محافظات التوصيل.', 'description_en' => 'Delete delivery zones.', 'sort_order' => 80],
        'settings.pricing.view' => ['group_key' => 'settings', 'name_ar' => 'عرض باقات الأسعار', 'name_en' => 'View pricing packages', 'description_ar' => 'عرض باقات الأسعار.', 'description_en' => 'View pricing packages.', 'sort_order' => 90],
        'settings.pricing.create' => ['group_key' => 'settings', 'name_ar' => 'إضافة باقات الأسعار', 'name_en' => 'Create pricing packages', 'description_ar' => 'إضافة باقات أسعار.', 'description_en' => 'Create pricing packages.', 'sort_order' => 100],
        'settings.pricing.update' => ['group_key' => 'settings', 'name_ar' => 'تعديل باقات الأسعار', 'name_en' => 'Update pricing packages', 'description_ar' => 'تعديل باقات الأسعار.', 'description_en' => 'Update pricing packages.', 'sort_order' => 110],
        'settings.pricing.delete' => ['group_key' => 'settings', 'name_ar' => 'حذف باقات الأسعار', 'name_en' => 'Delete pricing packages', 'description_ar' => 'حذف باقات الأسعار.', 'description_en' => 'Delete pricing packages.', 'sort_order' => 120],

        'admin_users.view' => ['group_key' => 'admin_users', 'name_ar' => 'عرض المشرفين', 'name_en' => 'View admin users', 'description_ar' => 'عرض قائمة حسابات المشرفين.', 'description_en' => 'View staff accounts.', 'sort_order' => 10, 'sensitive' => true],
        'admin_users.create' => ['group_key' => 'admin_users', 'name_ar' => 'إضافة مشرفين', 'name_en' => 'Create admin users', 'description_ar' => 'إنشاء حسابات مشرفين جديدة.', 'description_en' => 'Create new staff accounts.', 'sort_order' => 20, 'sensitive' => true],
        'admin_users.update' => ['group_key' => 'admin_users', 'name_ar' => 'تعديل المشرفين', 'name_en' => 'Update admin users', 'description_ar' => 'تعديل بيانات حسابات المشرفين.', 'description_en' => 'Update staff account details.', 'sort_order' => 30, 'sensitive' => true],
        'admin_users.delete' => ['group_key' => 'admin_users', 'name_ar' => 'حذف المشرفين', 'name_en' => 'Delete admin users', 'description_ar' => 'حذف حسابات المشرفين.', 'description_en' => 'Delete staff accounts.', 'sort_order' => 40, 'sensitive' => true],
        'admin_users.permissions.manage' => ['group_key' => 'admin_users', 'name_ar' => 'إدارة صلاحيات المشرفين', 'name_en' => 'Manage admin permissions', 'description_ar' => 'تعيين أو سحب الصلاحيات وتفعيل أو إيقاف حسابات المشرفين.', 'description_en' => 'Assign or revoke staff permissions and activate/deactivate staff accounts.', 'sort_order' => 50, 'sensitive' => true],

        'activity_logs.view' => ['group_key' => 'activity_logs', 'name_ar' => 'عرض سجل النشاط', 'name_en' => 'View activity logs', 'description_ar' => 'عرض سجل نشاط لوحة الإدارة.', 'description_en' => 'View admin activity logs.', 'sort_order' => 10, 'sensitive' => true],
    ],
];
